#--------------------------------------------------

### GET /api/some
GET {{hostname}}/some


### GET /
GET https://db.cineby.app/3/search/multi?language=en&page=1&query=whiplash&api_key=ad301b7cc82ffe19273e55e4d4206885


###
There is https://embed.su/ which I believe is used by cineby.
Otherwise check here : https://fmhy.net/videopiracyguide on the list on the right of the streaming sites there is a lot of "API" link 

https://www.omdbapi.com/