import type { Metadata } from "next";

export const metadata: Metadata = {
    title: {
        template: "%s | Sudo-Flix",
        default: "Sudo-Flix",
    },
    description: "Generated by create next app",
};
