import { Footer } from "app/components/shared/Footer";
import { Header } from "app/components/shared/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Fonts
const geistSans = localFont({
	src: "../fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "../fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: {
		template: "%s | Sudo-Flix",
		default: "Sudo-Flix",
	},
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>{/* head is for meta tags, title, styles, scripts, etc. */}</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
			>
				<Header />

				{/* Main content */}
				<main className="flex-grow">{children}</main>

				{/* Footer */}
				<Footer />
			</body>
		</html>
	);
}
